version: '3.8'  # Especifica la versión de Compose para utilizar características avanzadas

services:
  gitlab:
    image: gitlab/gitlab-ee:16.10.1-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.carlosmarind.cl'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.carlosmarind.cl'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    deploy:
      resources:
        limits:
          memory: 2G
    shm_size: '512m'  # Aumenta el tamaño de la memoria compartida si es necesario

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          memory: 1G

  nexus:
    image: sonatype/nexus3
    restart: always
    volumes:
      - nexus-data:/sonatype-work
    ports:
      - "8081:8081"
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 1G

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db_sonar
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db_sonar:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "8084:9000"
    deploy:
      resources:
        limits:
          memory: 2G

  db_sonar:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  jenkins_home:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
